LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

ENTITY ACC IS 
PORT(
	DATA_IN: IN STD_LOGIC_VECTOR(7 DOWNTO 0);
   IA: IN STD_LOGIC;
   EA: IN STD_LOGIC;
   CLK: IN STD_LOGIC;
   DATA_OUT: OUT STD_LOGIC_VECTOR(7 DOWNTO 0)
);
END ACC;

ARCHITECTURE A OF ACC IS
SIGNAL REGQ: STD_LOGIC_VECTOR(7 DOWNTO 0);
BEGIN
  PROCESS(IA,EA,CLK)
  BEGIN
   IF(CLK'EVENT AND CLK='1') THEN
     IF(IA='0') THEN
      REGQ<=DATA_IN;
     END IF;
   END IF;
  END PROCESS;
  DATA_OUT<= REGQ WHEN EA='0' ELSE "ZZZZZZZZ";
 END A;
